# Generated by Django 3.0.5 on 2020-04-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('RIB', models.CharField(max_length=150)),
                ('CardNb', models.CharField(max_length=150)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('RecieverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransactionReciever', to='wallet_api.User')),
                ('SenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransactionSender', to='wallet_api.User')),
            ],
        ),
    ]
